version: "3.9"

services:
  frontend:
    build: ./housing-expert/frontend
    container_name: housing-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./housing-expert/frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./housing-expert/backend
    container_name: housing-backend
    ports:
      - "5001:5000"
    volumes:
      - ./housing-expert/backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
